import type { EncyclopediaEntry } from '@/types';

export const DEFAULT_ENCYCLOPEDIA: EncyclopediaEntry[] = [
  {
    id: 'e1',
    materialId: 'm1',
    name: '檀香',
    aliases: ['旃檀', '白檀', '老山檀'],
    category: 'wood',
    origin: '印度、澳大利亚、印尼',
    priceRange: '2-10元/克',
    color: '#C4A882',
    fragranceNotes: {
      top: '清淡木质香',
      middle: '温润奶香',
      base: '厚重檀韵',
    },
    scentTags: ['温暖', '奶香', '木质', '温润', '安神'],
    pairingGood: ['沉香', '乳香', '安息香', '桂花', '玫瑰'],
    pairingAvoid: ['麝香', '龙脑'],
    usageTips: {
      dosageRange: '10%-40%',
      grindingNotes: '质地坚硬，需粗磨后再细研，研磨时会出油',
      suitableForms: ['stick', 'seal', 'fumigation', 'powder'],
    },
    culturalBackground: {
      history: '檀香自古即为佛家重要供养之物，有"香中之王"的美誉。印度老山檀最为名贵，树龄需三十年以上方能成材。',
      poetry: '苏轼《沉香山子赋》："旃檀紫檀，晨焚暮炷"',
      traditionalUse: '传统用于礼佛、安神、制作香牌等',
    },
    contributor: 'official',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'e2',
    materialId: 'm2',
    name: '沉香',
    aliases: ['沉水香', '奇楠', '海南沉'],
    category: 'wood',
    origin: '海南、越南、柬埔寨、印尼',
    priceRange: '15-500元/克',
    color: '#8B6F4E',
    fragranceNotes: {
      top: '清凉果香',
      middle: '蜜甜花香',
      base: '深沉木质底韵',
    },
    scentTags: ['清甜', '幽远', '蜜甜', '安神', '高贵'],
    pairingGood: ['檀香', '乳香', '安息香', '龙脑', '麝香'],
    pairingAvoid: ['丁香', '藿香'],
    usageTips: {
      dosageRange: '5%-20%',
      grindingNotes: '质地较软，含油脂丰富，研磨时温度不宜过高',
      suitableForms: ['stick', 'seal', 'fumigation', 'powder', 'cone'],
    },
    culturalBackground: {
      history: '沉香是瑞香科植物受真菌感染后结出的香脂，极为珍贵，素有"一两沉金"之说。',
      poetry: '李白《杨叛儿》："博山炉中沉香火，双烟一气凌紫霞"',
      traditionalUse: '古代宫廷熏香、文人雅士品香、药用等',
    },
    contributor: 'official',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'e3',
    materialId: 'm3',
    name: '丁香',
    aliases: ['公丁香', '母丁香', '丁子香'],
    category: 'herb',
    origin: '印尼、马来西亚、斯里兰卡',
    priceRange: '0.5-2元/克',
    color: '#A0522D',
    fragranceNotes: {
      top: '辛烈刺激',
      middle: '暖甜花香',
      base: '浓郁香料味',
    },
    scentTags: ['辛暖', '浓烈', '温暖', '提神'],
    pairingGood: ['肉桂', '肉豆蔻', '檀香', '桂花', '玫瑰'],
    pairingAvoid: ['薄荷', '龙脑（过量）'],
    usageTips: {
      dosageRange: '2%-8%',
      grindingNotes: '花蕾质地坚硬，研磨时需注意细度，粗颗粒会有辛辣感',
      suitableForms: ['stick', 'powder', 'cone'],
    },
    culturalBackground: {
      history: '丁香是古代丝绸之路重要的香料贸易品，中国自汉代已有使用记载。',
      poetry: '李商隐《代赠》："芭蕉不展丁香结，同向春风各自愁"',
      traditionalUse: '传统用于口香、调味、药用等',
    },
    contributor: 'official',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'e4',
    materialId: 'm4',
    name: '藿香',
    aliases: ['广藿香', '枝香', '南藿香'],
    category: 'herb',
    origin: '广东、广西、云南',
    priceRange: '0.2-0.8元/克',
    color: '#6B8E23',
    fragranceNotes: {
      top: '青草泥土香',
      middle: '浓郁药草香',
      base: '深沉泥土底韵',
    },
    scentTags: ['沉稳', '泥土', '药香', '辟秽'],
    pairingGood: ['苍术', '白芷', '丁香', '檀香', '乳香'],
    pairingAvoid: ['玫瑰', '桂花（花香类为主时）'],
    usageTips: {
      dosageRange: '5%-15%',
      grindingNotes: '全草入药，质地较脆，研磨后呈绿色粉末',
      suitableForms: ['stick', 'powder', 'seal'],
    },
    culturalBackground: {
      history: '藿香是中国传统本草的重要药材，《本草纲目》列为上品。',
      poetry: '苏轼《石菖蒲赞》："清芬酷烈，非独香也"',
      traditionalUse: '传统用于端午香囊、辟秽防疫、药用等',
    },
    contributor: 'official',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'e5',
    materialId: 'm5',
    name: '玫瑰',
    aliases: ['徘徊花', '刺玫花', '大马士革玫瑰'],
    category: 'flower',
    origin: '保加利亚、法国、中国甘肃',
    priceRange: '2-8元/克',
    color: '#D4756B',
    fragranceNotes: {
      top: '清甜花香',
      middle: '馥郁玫瑰香',
      base: '蜜甜底韵',
    },
    scentTags: ['甜美', '馥郁', '浪漫', '舒缓'],
    pairingGood: ['檀香', '安息香', '乳香', '桂花', '茉莉'],
    pairingAvoid: ['麝香（过量）', '藿香'],
    usageTips: {
      dosageRange: '5%-20%',
      grindingNotes: '花瓣娇嫩，宜轻研，过细会损失香气',
      suitableForms: ['stick', 'powder', 'fumigation', 'cone'],
    },
    culturalBackground: {
      history: '玫瑰是世界上最古老的香料花卉之一，古希腊罗马时期已广泛使用。',
      poetry: '温庭筠《菩萨蛮》："牡丹花谢莺声歇，绿杨满院中庭月"',
      traditionalUse: '传统用于香膏、香囊、美容、药用等',
    },
    contributor: 'official',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'e6',
    materialId: 'm6',
    name: '桂花',
    aliases: ['木犀', '岩桂', '金桂', '银桂'],
    category: 'flower',
    origin: '中国南方、四川、广西',
    priceRange: '3-10元/克',
    color: '#DAA520',
    fragranceNotes: {
      top: '清甜果香',
      middle: '浓郁桂花香',
      base: '蜜糖甜韵',
    },
    scentTags: ['清甜', '浓郁', '喜庆', '温暖'],
    pairingGood: ['檀香', '沉香', '安息香', '玫瑰', '茉莉'],
    pairingAvoid: ['薄荷', '龙脑'],
    usageTips: {
      dosageRange: '5%-15%',
      grindingNotes: '花朵细小，干花质脆，宜用低温研磨',
      suitableForms: ['stick', 'powder', 'fumigation', 'seal'],
    },
    culturalBackground: {
      history: '桂花是中国传统十大名花之一，栽培历史超过2500年。',
      poetry: '王维《鸟鸣涧》："人闲桂花落，夜静春山空"',
      traditionalUse: '传统用于桂花糕、桂花酒、香囊等',
    },
    contributor: 'official',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'e7',
    materialId: 'm7',
    name: '乳香',
    aliases: ['薰陆香', '马尾香', '索马里乳香'],
    category: 'resin',
    origin: '索马里、埃塞俄比亚、阿拉伯半岛',
    priceRange: '3-12元/克',
    color: '#F5DEB3',
    fragranceNotes: {
      top: '柑橘清香',
      middle: '温暖树脂香',
      base: '木质苦香底韵',
    },
    scentTags: ['清灵', '通透', '神圣', '净化'],
    pairingGood: ['没药', '檀香', '沉香', '安息香', '玫瑰'],
    pairingAvoid: ['丁香（过量）'],
    usageTips: {
      dosageRange: '5%-20%',
      grindingNotes: '树脂类，易粘黏，需冷藏后研磨，或掺入其他粉一同研磨',
      suitableForms: ['fumigation', 'stick', 'powder', 'cone'],
    },
    culturalBackground: {
      history: '乳香是古代香料贸易的核心商品，比黄金还珍贵，被誉为"天堂的眼泪"。',
      poetry: '圣经记载东方三博士以乳香、没药、黄金赠予耶稣',
      traditionalUse: '传统用于宗教仪式、医用、防腐等',
    },
    contributor: 'official',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'e8',
    materialId: 'm8',
    name: '没药',
    aliases: ['末药', '明没药', '阿拉伯没药'],
    category: 'resin',
    origin: '索马里、埃塞俄比亚、阿拉伯半岛',
    priceRange: '4-15元/克',
    color: '#A0522D',
    fragranceNotes: {
      top: '微苦药香',
      middle: '浓郁树脂香',
      base: '深沉苦甜底韵',
    },
    scentTags: ['温厚', '深沉', '药香', '治愈'],
    pairingGood: ['乳香', '檀香', '沉香', '安息香', '肉桂'],
    pairingAvoid: ['玫瑰（花香为主时）'],
    usageTips: {
      dosageRange: '3%-15%',
      grindingNotes: '质地坚硬，需粗碎后细研，易出油粘黏',
      suitableForms: ['fumigation', 'stick', 'powder'],
    },
    culturalBackground: {
      history: '没药与乳香齐名，是古代香料贸易的重要商品，古埃及人用于木乃伊防腐。',
      poetry: '圣经诗篇："我以我的良人为一袋没药，常在我怀中"',
      traditionalUse: '传统用于药用、防腐、宗教仪式等',
    },
    contributor: 'official',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'e9',
    materialId: 'm9',
    name: '龙脑',
    aliases: ['冰片', '龙脑香', '梅花脑'],
    category: 'mineral',
    origin: '印尼苏门答腊、中国广东',
    priceRange: '15-50元/克',
    color: '#E0E8F0',
    fragranceNotes: {
      top: '强烈清凉感',
      middle: '通透木质香',
      base: '几乎无残留',
    },
    scentTags: ['清凉', '通透', '提神', '开窍'],
    pairingGood: ['檀香', '沉香', '乳香', '安息香', '麝香'],
    pairingAvoid: ['丁香（过量）', '玫瑰（花香为主时）'],
    usageTips: {
      dosageRange: '1%-5%',
      grindingNotes: '质地松脆，极易研细，但挥发性强，需密封保存',
      suitableForms: ['stick', 'powder', 'fumigation'],
    },
    culturalBackground: {
      history: '龙脑香是古代珍贵香料，汉代即已传入中国，被誉为"香中之首"。',
      poetry: '花蕊夫人《宫词》："青锦地衣红绣毯，尽铺龙脑郁金香"',
      traditionalUse: '传统用于药用开窍、熏香、制作香牌等',
    },
    contributor: 'official',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'e10',
    materialId: 'm10',
    name: '麝香',
    aliases: ['元寸香', '当门子', '人工麝香'],
    category: 'mineral',
    origin: '中国西南、青藏高原',
    priceRange: '30-200元/克',
    color: '#D2B48C',
    fragranceNotes: {
      top: '微腥动物香',
      middle: '温暖性感香',
      base: '持久浓郁底韵',
    },
    scentTags: ['浓郁', '持久', '性感', '定香'],
    pairingGood: ['檀香', '沉香', '龙脑', '安息香', '乳香'],
    pairingAvoid: ['薄荷', '藿香'],
    usageTips: {
      dosageRange: '0.5%-3%',
      grindingNotes: '极少量即可，需与其他香粉充分混合，直接接触皮肤可能过敏',
      suitableForms: ['stick', 'powder', 'fumigation'],
    },
    culturalBackground: {
      history: '麝香是极为珍贵的动物香料，自古即为宫廷御用，有"诸香之冠"美誉。',
      poetry: '杜甫《丁香》："晚堕兰麝中，休怀粉身念"',
      traditionalUse: '传统用于药用开窍、定香、春药等',
    },
    contributor: 'official',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'e11',
    materialId: 'm11',
    name: '安息香',
    aliases: ['金银香', '苏门答腊安息香', '暹罗安息香'],
    category: 'resin',
    origin: '印尼苏门答腊、泰国、越南',
    priceRange: '2-8元/克',
    color: '#DEB887',
    fragranceNotes: {
      top: '甜美香草香',
      middle: '温暖树脂香',
      base: '深沉甜香底韵',
    },
    scentTags: ['甜美', '温暖', '安抚', '助眠'],
    pairingGood: ['檀香', '沉香', '乳香', '没药', '玫瑰'],
    pairingAvoid: ['薄荷', '龙脑（过量）'],
    usageTips: {
      dosageRange: '5%-20%',
      grindingNotes: '树脂类，质脆易碎，研磨时易粘黏',
      suitableForms: ['stick', 'fumigation', 'powder', 'cone'],
    },
    culturalBackground: {
      history: '安息香因"安息"二字而闻名，古人认为其能安神助眠、驱逐邪气。',
      poetry: '李时珍《本草纲目》："安息香，辟恶，安息诸邪"',
      traditionalUse: '传统用于药用、熏香安神、祭祀等',
    },
    contributor: 'official',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'e12',
    materialId: 'm12',
    name: '甘松',
    aliases: ['甘松香', '香松', '四川甘松'],
    category: 'herb',
    origin: '四川、甘肃、青海',
    priceRange: '0.8-3元/克',
    color: '#8FBC8F',
    fragranceNotes: {
      top: '泥土根茎香',
      middle: '浓郁草木香',
      base: '沉稳苦甜底韵',
    },
    scentTags: ['泥土', '沉稳', '草木', '辟秽'],
    pairingGood: ['檀香', '乳香', '安息香', '苍术', '白芷'],
    pairingAvoid: ['玫瑰', '茉莉（花香为主时）'],
    usageTips: {
      dosageRange: '5%-15%',
      grindingNotes: '根茎类药材，质地较硬，研磨后呈棕绿色粉末',
      suitableForms: ['stick', 'powder', 'seal'],
    },
    culturalBackground: {
      history: '甘松是中国传统香料，唐代即已用于合香，是著名的"辅香"之一。',
      poetry: '白居易《后宫词》："泪湿罗巾梦不成，夜深前殿按歌声"',
      traditionalUse: '传统用于合香、药用、香囊等',
    },
    contributor: 'official',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'e13',
    materialId: 'm13',
    name: '龙涎香',
    aliases: ['龙腹香', '鲸涎香', '灰琥珀'],
    category: 'mineral',
    origin: '印度洋、太平洋沿岸',
    priceRange: '500-5000元/克',
    color: '#696969',
    fragranceNotes: {
      top: '微腥海味',
      middle: '温暖木质香',
      base: '极其持久的甜香底韵',
    },
    scentTags: ['珍贵', '持久', '定香', '高贵'],
    pairingGood: ['檀香', '沉香', '麝香', '乳香', '安息香'],
    pairingAvoid: ['薄荷', '藿香'],
    usageTips: {
      dosageRange: '0.1%-1%',
      grindingNotes: '极其珍贵，极少量即可，需精细研磨后与其他香粉充分混合',
      suitableForms: ['stick', 'powder', 'fumigation'],
    },
    culturalBackground: {
      history: '龙涎香是抹香鲸的分泌物，是世界上最珍贵的香料之一，被誉为"灰色黄金"。',
      poetry: '苏轼《沉香山子赋》："如神龙之蜿蜒，吐祥云而郁律"',
      traditionalUse: '传统用于宫廷御用、定香、药用等',
    },
    contributor: 'official',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'e14',
    materialId: 'm14',
    name: '茉莉',
    aliases: ['茉莉花', '抹丽', '小南强'],
    category: 'flower',
    origin: '中国福建、广西、印度',
    priceRange: '4-12元/克',
    color: '#FFFAF0',
    fragranceNotes: {
      top: '清新花香',
      middle: '浓郁茉莉香',
      base: '清甜底韵',
    },
    scentTags: ['清新', '浓郁', '高雅', '舒缓'],
    pairingGood: ['檀香', '沉香', '玫瑰', '桂花', '安息香'],
    pairingAvoid: ['藿香', '苍术'],
    usageTips: {
      dosageRange: '5%-15%',
      grindingNotes: '花朵娇嫩，干花易碎，宜轻研',
      suitableForms: ['stick', 'powder', 'fumigation', 'seal'],
    },
    culturalBackground: {
      history: '茉莉自汉代传入中国，宋代已广受欢迎，被誉为"人间第一香"。',
      poetry: '柳永《合欢带》："知几度、密约秦楼尽醉，仍携手，眷恋香衾绣被"',
      traditionalUse: '传统用于窨茶、香囊、熏香、美容等',
    },
    contributor: 'official',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'e15',
    materialId: 'm15',
    name: '柏木',
    aliases: ['侧柏', '柏子', '香柏'],
    category: 'wood',
    origin: '中国各地',
    priceRange: '0.3-2元/克',
    color: '#8B7355',
    fragranceNotes: {
      top: '清新松香',
      middle: '温润木质香',
      base: '深沉松柏底韵',
    },
    scentTags: ['清新', '木质', '松柏', '安神'],
    pairingGood: ['檀香', '沉香', '乳香', '安息香', '松针'],
    pairingAvoid: ['玫瑰', '茉莉（花香为主时）'],
    usageTips: {
      dosageRange: '10%-30%',
      grindingNotes: '木质坚硬，需粗磨后再细研',
      suitableForms: ['stick', 'seal', 'powder', 'cone'],
    },
    culturalBackground: {
      history: '柏树在中国文化中象征长寿与气节，古人常以柏香祭祀。',
      poetry: '杜甫《古柏行》："孔明庙前有老柏，柯如青铜根如石"',
      traditionalUse: '传统用于祭祀、安神、药用等',
    },
    contributor: 'official',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'e16',
    materialId: 'm16',
    name: '白芷',
    aliases: ['芳香', '泽芬', '川白芷'],
    category: 'herb',
    origin: '四川、浙江、河南',
    priceRange: '0.5-2元/克',
    color: '#F5F5DC',
    fragranceNotes: {
      top: '辛香药草味',
      middle: '浓郁根茎香',
      base: '微苦底韵',
    },
    scentTags: ['辛香', '辟秽', '药香', '通透'],
    pairingGood: ['藿香', '苍术', '丁香', '檀香', '柏木'],
    pairingAvoid: ['玫瑰', '茉莉'],
    usageTips: {
      dosageRange: '5%-15%',
      grindingNotes: '根茎类，质地较硬，研磨后呈白色粉末',
      suitableForms: ['stick', 'powder', 'seal'],
    },
    culturalBackground: {
      history: '白芷是中国传统本草的重要药材，《神农本草经》列为中品。',
      poetry: '屈原《九歌》："白芷兮兰生，纫秋兰以为佩"',
      traditionalUse: '传统用于端午香囊、药用、美容等',
    },
    contributor: 'official',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'e17',
    materialId: 'm17',
    name: '肉桂',
    aliases: ['玉桂', '官桂', '桂皮'],
    category: 'herb',
    origin: '广西、广东、云南、越南',
    priceRange: '1-5元/克',
    color: '#8B4513',
    fragranceNotes: {
      top: '辛甜香料香',
      middle: '温暖肉桂香',
      base: '深沉辛辣底韵',
    },
    scentTags: ['温暖', '辛甜', '香料', '提神'],
    pairingGood: ['丁香', '肉豆蔻', '檀香', '安息香', '玫瑰'],
    pairingAvoid: ['薄荷', '龙脑'],
    usageTips: {
      dosageRange: '3%-10%',
      grindingNotes: '树皮类，质地较硬，宜用肉桂皮，研磨后香气浓郁',
      suitableForms: ['stick', 'powder', 'cone'],
    },
    culturalBackground: {
      history: '肉桂是古代丝绸之路的重要香料，中国使用历史超过2000年。',
      poetry: '杜牧《阿房宫赋》："烟斜雾横，焚椒兰也"',
      traditionalUse: '传统用于调味、药用、香身等',
    },
    contributor: 'official',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'e18',
    materialId: 'm18',
    name: '苍术',
    aliases: ['赤术', '青术', '茅苍术'],
    category: 'herb',
    origin: '江苏、湖北、河南',
    priceRange: '0.5-2元/克',
    color: '#A0522D',
    fragranceNotes: {
      top: '辛烈药香',
      middle: '浓郁根茎香',
      base: '微苦底韵',
    },
    scentTags: ['辛烈', '辟秽', '药香', '燥湿'],
    pairingGood: ['藿香', '白芷', '丁香', '檀香', '柏木'],
    pairingAvoid: ['玫瑰', '茉莉（花香为主时）'],
    usageTips: {
      dosageRange: '5%-12%',
      grindingNotes: '根茎类，质地坚实，研磨后呈棕黄色粉末，有朱砂点',
      suitableForms: ['stick', 'powder', 'seal'],
    },
    culturalBackground: {
      history: '苍术是中国传统避疫名药，古人认为其能"除恶气，弭灾沴"。',
      poetry: '李时珍《本草纲目》："苍术，消痰水，解湿郁"',
      traditionalUse: '传统用于端午熏烟、辟秽防疫、药用等',
    },
    contributor: 'official',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'e19',
    materialId: 'm19',
    name: '薰衣草',
    aliases: ['灵香草', '香草', '拉文德'],
    category: 'flower',
    origin: '法国普罗旺斯、新疆伊犁',
    priceRange: '2-6元/克',
    color: '#9370DB',
    fragranceNotes: {
      top: '清新草香',
      middle: '浓郁薰衣草香',
      base: '舒缓甜香底韵',
    },
    scentTags: ['舒缓', '安眠', '清新', '草本'],
    pairingGood: ['玫瑰', '檀香', '乳香', '安息香', '洋甘菊'],
    pairingAvoid: ['丁香', '肉桂'],
    usageTips: {
      dosageRange: '5%-15%',
      grindingNotes: '花朵娇嫩，干花质轻，宜轻研，过细会损失香气',
      suitableForms: ['stick', 'powder', 'fumigation', 'cone'],
    },
    culturalBackground: {
      history: '薰衣草是西方最著名的香草之一，古罗马时期已用于沐浴香身。',
      poetry: '欧洲传统婚礼常用薰衣草象征幸福与纯洁',
      traditionalUse: '传统用于香包、助眠、护肤、驱虫等',
    },
    contributor: 'official',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'e20',
    materialId: 'm20',
    name: '陈皮',
    aliases: ['橘皮', '广陈皮', '新会皮'],
    category: 'herb',
    origin: '广东新会、福建、四川',
    priceRange: '1-8元/克',
    color: '#CD853F',
    fragranceNotes: {
      top: '清新柑橘香',
      middle: '成熟果香',
      base: '陈香苦甜底韵',
    },
    scentTags: ['清新', '果香', '陈香', '理气'],
    pairingGood: ['檀香', '安息香', '丁香', '肉桂', '玫瑰'],
    pairingAvoid: ['薄荷', '龙脑'],
    usageTips: {
      dosageRange: '5%-15%',
      grindingNotes: '果皮类，质脆易碎，越陈越香，研磨后呈橙黄色粉末',
      suitableForms: ['stick', 'powder', 'seal'],
    },
    culturalBackground: {
      history: '陈皮是中国传统药食两用品，广东新会陈皮最为名贵，素有"一两陈皮一两金"之说。',
      poetry: '苏轼《食荔枝》："日啖荔枝三百颗，不辞长作岭南人"',
      traditionalUse: '传统用于药用、调味、熏香等',
    },
    contributor: 'official',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'e21',
    materialId: 'm21',
    name: '奇楠香',
    aliases: ['棋楠', '伽南香', '奇蓝'],
    category: 'wood',
    origin: '越南、柬埔寨、海南',
    priceRange: '100-2000元/克',
    color: '#3D2B1F',
    fragranceNotes: {
      top: '清凉通透',
      middle: '蜜甜花香',
      base: '深沉乳香底韵',
    },
    scentTags: ['通透', '蜜甜', '变幻', '珍贵'],
    pairingGood: ['沉香', '檀香', '龙脑', '麝香', '乳香'],
    pairingAvoid: ['藿香', '苍术'],
    usageTips: {
      dosageRange: '1%-5%',
      grindingNotes: '质地较软，油脂丰富，研磨时易出油，需低温研磨',
      suitableForms: ['fumigation', 'stick', 'powder'],
    },
    culturalBackground: {
      history: '奇楠是沉香中的极品，被誉为"香中之王"，质地较软，香气层次丰富多变。',
      poetry: '宋代蔡绦《铁围山丛谈》："香木，初与沉香俱生，而结特久"',
      traditionalUse: '传统用于品香收藏、药用、宗教仪式等',
    },
    contributor: 'official',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'e22',
    materialId: 'm22',
    name: '崖柏',
    aliases: ['太行崖柏', '侧柏', '香柏'],
    category: 'wood',
    origin: '太行山、秦岭、四川',
    priceRange: '5-50元/克',
    color: '#8B4513',
    fragranceNotes: {
      top: '清甜松香',
      middle: '浓郁木质香',
      base: '深沉醇厚底韵',
    },
    scentTags: ['醇厚', '松香', '安神', '天然'],
    pairingGood: ['檀香', '沉香', '乳香', '安息香', '松针'],
    pairingAvoid: ['玫瑰', '茉莉'],
    usageTips: {
      dosageRange: '10%-30%',
      grindingNotes: '木质坚硬，需粗磨后细研，老料油性足，研磨时会出油',
      suitableForms: ['stick', 'seal', 'powder', 'fumigation'],
    },
    culturalBackground: {
      history: '崖柏生长于悬崖峭壁之上，历经千年而成，近年来成为收藏新宠。',
      poetry: '李白《蜀道难》："黄鹤之飞尚不得过，猿猱欲度愁攀援"',
      traditionalUse: '传统用于雕刻、熏香、药用等',
    },
    contributor: 'official',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
  },
];
